services:
  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: interview-platform-postgres
    environment:
      POSTGRES_DB: interview_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - interview-platform-data:/var/lib/postgresql/data
    networks:
      - platform-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d interview_platform"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Go Auth gRPC Service
  auth-service:
    container_name: interview-platform-auth
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - SERVER_PORT=50051
      - POSTGRES_DSN=Host=postgres;Port=5432;Database=interview_platform;Username=postgres;Password=postgres
      - JWT_SECRET=InterviewPlatformPracticeSecret_ChangeForProduction_2026
      - JWT_ISSUER=InterviewPlatform
      - JWT_AUDIENCE=InterviewPlatform
      - JWT_EXPIRY=120m
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - platform-network

  # Backend .NET 10
  backend:
    container_name: interview-platform-backend
    build:
      context: .
      dockerfile: src/InterviewPlatform.API/Dockerfile
    ports:
      - "5126:5126"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=interview_platform;Username=postgres;Password=postgres
      - GrpcAuth__Address=http://auth-service:50051
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
    networks:
      - platform-network

  # 3. Frontend React
  frontend:
    container_name: interview-platform-frontend
    build:
      context: .
      dockerfile: ui/Dockerfile
    ports:
      - "3000:80" # Откроется на http://localhost:3000
    depends_on:
      - backend
    networks:
      - platform-network

volumes:
  interview-platform-data:

networks:
  platform-network:
    driver: bridge