export const PERMISSION_GROUPS = {
  'Кандидаты': ['candidates.view', 'candidates.create', 'candidates.edit', 'candidates.archive', 'candidates.delete'],
  'Вакансии': ['vacancies.view', 'vacancies.create', 'vacancies.edit', 'vacancies.archive', 'vacancies.delete'],
  'Собеседования': ['interviews.view', 'interviews.create', 'interviews.edit', 'interviews.decide', 'interviews.canInterview'],
  'Компетенции (оценка)': ['matrix.view', 'matrix.edit'],
  'Компетенции (справочник)': ['competencies.view', 'competencies.create', 'competencies.edit', 'competencies.archive', 'competencies.delete'],
  'Пользователи': ['users.view', 'users.create', 'users.edit', 'users.delete'],
  'Журнал': ['logs.view'],
  'Архив': ['archive.view'],
  'Главная': ['dashboard.view'],
};

export const PERMISSION_LABELS = {
  'candidates.view': 'Просмотр кандидатов',
  'candidates.create': 'Добавление кандидатов',
  'candidates.edit': 'Редактирование кандидатов',
  'candidates.archive': 'Архивация кандидатов',
  'candidates.delete': 'Удаление кандидатов',
  'vacancies.view': 'Просмотр вакансий',
  'vacancies.create': 'Создание вакансий',
  'vacancies.edit': 'Редактирование вакансий',
  'vacancies.archive': 'Архивация вакансий',
  'vacancies.delete': 'Удаление вакансий',
  'interviews.view': 'Просмотр собеседований',
  'interviews.create': 'Планирование собеседований',
  'interviews.edit': 'Редактирование собеседований',
  'interviews.decide': 'Принятие решений',
  'interviews.canInterview': 'Может быть интервьюером',
  'matrix.view': 'Просмотр оценок',
  'matrix.edit': 'Редактирование оценок',
  'competencies.view': 'Просмотр компетенций',
  'competencies.create': 'Создание компетенций',
  'competencies.edit': 'Редактирование компетенций',
  'competencies.archive': 'Архивация компетенций',
  'competencies.delete': 'Удаление компетенций',
  'users.view': 'Просмотр пользователей',
  'users.create': 'Создание пользователей',
  'users.edit': 'Редактирование пользователей',
  'users.delete': 'Удаление пользователей',
  'logs.view': 'Просмотр журнала',
  'archive.view': 'Просмотр архива',
  'dashboard.view': 'Главная страница',
};
